### ISSUE TITLE
Usage of the --gpu flag produces an error.

### ISSUE THREAD

**Issue by PlexSheep** [johndoe31415/nvfanctrl#1]
The use of the --gpu flag produces an error, regardless of which GPU I am trying to control.

Example 1 ( for GPU 1 )
```
$ ./nvfanctrl.py --gpu 1 -t 55
Traceback (most recent call last):
  File "./nvfanctrl.py", line 119, in <module>
    regulator = NvidiaRegulator(args)
  File "./nvfanctrl.py", line 41, in __init__
    subprocess.check_call([ "nvidia-settings", "--assign", "[%s]/GPUFanControlState=1" % (self._args.gpu) ], stdout = subprocess.DEVNULL, stderr = subprocess.DEVNULL)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nvidia-settings', '--assign', '[1]/GPUFanControlState=1']' returned non-zero exit status 1.
```

Example 2 ( for GPU 0 )
```
$ ./nvfanctrl.py --gpu 0 -t 55
Traceback (most recent call last):
  File "./nvfanctrl.py", line 119, in <module>
    regulator = NvidiaRegulator(args)
  File "./nvfanctrl.py", line 41, in __init__
    subprocess.check_call([ "nvidia-settings", "--assign", "[%s]/GPUFanControlState=1" % (self._args.gpu) ], stdout = subprocess.DEVNULL, stderr = subprocess.DEVNULL)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nvidia-settings', '--assign', '[0]/GPUFanControlState=1']' returned non-zero exit status 1.
```

I think the 3rd argument is the reason for this error. When I try to put in the commands listed in the traceback manually i get the following in zsh:
```
$ nvidia-settings --assign [1]/GPUFanControlState=1
zsh: no matches found: [1]/GPUFanControlState=1

```

And the following in bash:
```
$ nvidia-settings --assign [1]/GPUFanControlState=1               


ERROR: Error resolving target specification '1' (No targets match target specification), specified in assignment '[1]/GPUFanControlState=1'.
```

Playing around with that 3rd argument, i noticed variations without the braces seem to produce more useful things. I might fork this project to see if i can fix it.

```
nvidia-settings --version

nvidia-settings:  version 470.57.01
  The NVIDIA X Server Settings tool.

  This program is used to configure the NVIDIA Linux graphics driver.
  For more detail, please see the nvidia-settings(1) man page.
```

(I have a dual GPU setup and want to change the behavior of GPU 1)

![image](https://user-images.githubusercontent.com/58274330/204141793-2cae8587-ca70-4fab-ba08-5f202bc3de85.png)

**Comment by johndoe31415** [comment]
Hi, it's been a while since I wrote this piece of software and I've since migrated to a Radeon, so I cannot directly test your issue.

One thing that strikes me is that the default parameter for -g is "gpu:0" while you're putting simply "1". Have you tried "gpu:1" and can verify if that fixes things?

**Comment by PlexSheep** [comment]
Using gpu:X instead of just X after the option works. Seem i over read that part in --help. It seem to be working now, unfortunately my old 750 Ti still roars up to high percentages from time to time. I have had this problem for a long time, it's probably a hardware issue.

I have forked your project, if I have time I might make a couple of improvements.
